spring.application.name=backend

# Configuración acceso base de datos 

spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3307/app_facturacion
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Declaración de variables para trabajar con seguridad

jwt.secret=FnkSB6FaeCrkUdKeREOxpH229t+nbuMokYivKNLVtD8=
jwt.expiration=86400000